module.exports = {
	printWidth: 80,
	tabWidth: 2,
	trailingComma: "es5",
	singleQuote: false,
	semi: true,
	importOrder: [
		"^react",
		"^react-dom/(.*)$",
		"^react-map-gl/(.*)$",
		"^react-transition-group/(.*)$",
		"^react-icons/(.*)$",
		"^react-select/(.*)$",
		"^react-bootstrap/(.*)$",
		"^next/(.*)$",
		"^@/components/(.*)$",
		"^@/lib/(.*)$",
		"^@/context/(.*)$",
		"^classnames",
		"^[./]",
	],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	arrowParens: "always",
	bracketSpacing: true,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	insertPragma: false,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	useTabs: true,
	vueIndentScriptAndStyle: false,
	parser: "babel",
};
