const base = {
	MAPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN,
	MAPBOX_STYLE_URL: process.env.NEXT_PUBLIC_MAPBOX_STYLE_URL,
	WESALE_API_URL: process.env.NEXT_PUBLIC_API_URL,
};

export const { WESALE_API_URL, MAPBOX_ACCESS_TOKEN, MAPBOX_STYLE_URL } = base;
